### ISSUE TITLE
Character slows down when picking up health

### ISSUE THREAD

**Issue by Caleb10E** [DYatesFSU/InstructorOfTheDead#29]
When the player character touches a health item, he stops/slows down as he picks it up. The character should keep moving at full speed when he picks up health.

**Comment by JagvirS** [comment]
it is because the event takes place on hit rather than overlap. will have to tinker around with the collision presets so that overlap can work, similar to the MyProjectile. 
gonna look into it

**Comment by JagvirS** [comment]
we had changed character collision to block all.  i think it was when we were trying to fix MyPrjectile collision.
-changed character collision to default
-changed energyball sprite to no collision
-added sphere collision on energyball with on begin overlap event
