### ISSUE TITLE
Healthbar on enemy does not respond to "projectile"

### ISSUE THREAD

**Issue by mansaa0n** [DYatesFSU/InstructorOfTheDead#45]
I am trying to make the healthbar on the enemy to respond to the "projectile" object so enemy loses life (Healthbar decreases..) before the graduation day .... I couldn't find why it does not respond to my codes... HELPPPP!

**Comment by JagvirS** [comment]
i got it

**Comment by JagvirS** [comment]
you never actually ran the update code, added a sequence node from takeDamage
