### ISSUE TITLE
Final Destination performance issues with all enemy types

### ISSUE THREAD

**Issue by Caleb10E** [DYatesFSU/InstructorOfTheDead#52]
Performance is still choppy on the Final Destination level. Now that little enemies spawn during the boss fight, I've noticed that the stuttering happens when you shoot at those enemies as well as the boss. Not sure how, but maybe it has something to do with the level, but I'm not positive.

**Comment by DYatesFSU** [comment]
Check the custom level for the shooter enemy type as well, that one was lagging when the player collided with the enemy projectile as well.

**Comment by Caleb10E** [comment]
Solved with lighting change
